### ISSUE TITLE
Step to integrate 

### ISSUE THREAD

**Issue by shiva-p17** [rahulreghunath/Textlocal#1]
Hi
Can you please provide a steps to integrate Text local with laravel

Thanks

**Comment by rahulreghunath** [comment]
yeah sure,
register the package in config/app.php by adding `Rahulreghunath\Textlocal\ServiceProvider::class,` to the provider section ( automatic package discovery is available if you using laravel 5.5.0 or later ).
run `php artisan vendor:publish` and publish the vendor, and textlocal.php file will be available in your config folder. paste your credentials there and you are good to go.
```
$sms = new Textlocal();
$sms->send('your message','your number');
```
