### ISSUE TITLE
Class 'Rahulreghunath\Textlocal\ServiceProvider' not found - When Deployed

### ISSUE THREAD

**Issue by mikeejk** [rahulreghunath/Textlocal#4]
Hi there,

I Am trying to Integrate Textlocal

In local its working fine. But when deployed, it says "Class 'Rahulreghunath\Textlocal\ServiceProvider' not found".

I followed the steps and added in providers array too. Also, Vendor Published

In Controller - use Rahulreghunath\Textlocal\ServiceProvider;

Am I missing something

Can you please help it out.

**Comment by mikeejk** [comment]
> Hi there,
> 
> I Am trying to Integrate Textlocal
> 
> In local its working fine. But when deployed, it says "Class 'Rahulreghunath\Textlocal\ServiceProvider' not found".
> 
> I followed the steps and added in providers array too. Also, Vendor Published
> 
> In Controller - use Rahulreghunath\Textlocal\ServiceProvider;
> 
> Am I missing something
> 
> Can you please help it out.

I Missed the Package in the server. Its working

**Comment by rahulreghunath** [comment]
cool :+1:
